// ============================================================
// NRNF26 — languages.js
// Multi-language support: NL (default), EN, DE
// Usage: t('key') returns string in current language
// ============================================================

const TRANSLATIONS = {
  nl: {

    // AUTH
    auth_title: "NO RISK NO FUN",
    auth_sub: "⚽ WK POOL 2026 ⚽",
    auth_label_email: "E-MAILADRES",
    auth_label_password: "WACHTWOORD",
    auth_label_username: "GEBRUIKERSNAAM",
    auth_placeholder_email: "jouw@email.nl",
    auth_placeholder_password: "••••••••",
    auth_placeholder_username: "bijv. niels99",
    auth_placeholder_password_min: "min. 6 tekens",
    auth_btn_login: "INLOGGEN ▶",
    auth_btn_register: "AANMELDEN ▶",
    auth_toggle_to_register: "Geen account? Registreren",
    auth_toggle_to_login: "Al een account? Inloggen",
    auth_err_wrong_credentials: "✗ Verkeerd e-mail of wachtwoord.",
    auth_err_username_too_short: "✗ Gebruikersnaam te kort.",
    auth_err_password_too_short: "✗ Wachtwoord min. 6 tekens.",
    auth_err_username_taken: "✗ Gebruikersnaam al in gebruik.",
    auth_err_profile_not_found: "✗ Profiel niet gevonden.",

    // HEADER
    header_logo_title: "NO RISK NO FUN",
    header_logo_sub: "⚽ WK POOL 2026 ⚽",
    header_logged_in_as: "ingelogd als",
    header_btn_logout: "UITLOGGEN",

    // NAVIGATION
    nav_home: "🏠 HOME",
    nav_tips: "⚽ TIPS",
    nav_stand: "🏆 STAND",
    nav_spelregels: "📖 SPELREGELS",
    nav_toernooi: "📋 TOERNOOI",
    nav_admin: "⚙ ADMIN",

    // HOME
    home_section_title: "▶ HOME",
    home_label_podium: "PODIUM GISTEREN",
    home_label_stats: "STATISTIEKEN",
    home_label_complot: "COMPLOTGROEPJES",
    home_loading: "Laden...",
    home_no_matches_yet: "Nog geen wedstrijden gespeeld.",

    // PODIUM
    podium_rank_1: "★ 1ST · CHAMPION ★",
    podium_rank_2: "2ND · SILVER",
    podium_rank_3: "3RD · BRONZE",
    podium_stat_streak: "STREAK",
    podium_stat_risk: "RISICO",
    podium_stat_day_wins: "DAGWINSTEN",
    podium_day_total: "dag totaal",

    // STATS TICKERS
    stat_ticker_waaghals_label: "🎲 WAAGHALS VAN VANDAAG",
    stat_ticker_streak_label: "🔥 HEISSESTE STREAK",
    stat_ticker_oddsbeater_label: "🎯 ODDS BEATER",
    stat_ticker_hint: "▶ klik voor volledig overzicht",
    stat_ticker_avg_chance: "gem. {X}% kans",
    stat_ticker_under_fav: "{X}% gem. onder favoriet",
    stats_no_data_yet: "Stats beschikbaar na de eerste speeldag.",

    // STATS MODAL
    stats_modal_waaghals_title: "🎲 WAAGHALS RANKING",
    stats_modal_waaghals_sub: "Lagere gem. kans = meer risico genomen",
    stats_modal_streaks_title: "🔥 STREAK OVERZICHT",
    stats_modal_streaks_longest: "langste: {X}",
    stats_modal_oddsbeater_title: "🎯 ODDS BEATER RANKING",
    stats_modal_oddsbeater_sub: "Wint terwijl ze niet op de favoriet gokken",
    stats_modal_oddsbeater_hits: "{X}× raak · {Y} pts",
    stats_modal_no_data: "Geen data.",
    stats_modal_btn_close: "✕ SLUITEN",

    // COMPLOT
    complot_empty_title: "JIJ WEET NOG NIETS",
    complot_empty_body: "Je zit nog vast in de matrix. Ontsnap zelf of wacht tot iemand je eruit haalt.",
    complot_btn_create: "🐓 COMPLOT AANMAKEN",
    complot_btn_new: "+ NIEUW COMPLOT",
    complot_member_count: "{X} leden",
    complot_label_ranking: "KLASSEMENT",
    complot_haantje_powers_label: "🐓 HAANTJE POWERS",
    complot_btn_wake_up: "🐑 Slaper wakker maken",
    complot_btn_manage: "🐓 Complot beheren",
    complot_haantje_badge: "🐓 HAANTJE",
    complot_prompt_name: "Naam van je complotgroepje:",

    // COMPLOT MANAGE MODAL
    complot_manage_title: "BEHEER HET COMPLOT 🐓",
    complot_manage_invite_link_label: "INVITE LINK",
    complot_manage_btn_copy_link: "📋 KOPIEER LINK",
    complot_manage_recruit_label: "🐑 SCHAAP REKRUTEREN",
    complot_manage_username_label: "Gebruikersnaam van de slaapkop:",
    complot_manage_username_placeholder: "gebruikersnaam...",
    complot_manage_btn_wake_up: "💊 WAKKER MAKEN",
    complot_action_btn_crown: "🐓👑 Kronen",
    complot_action_btn_sleep: "😴 Laten slapen",
    complot_action_tooltip_crown: "Maak dit lid ook Haantje",
    complot_action_tooltip_sleep: "Stuur terug de matrix in",
    complot_modal_btn_close: "✕ SLUITEN",

    // INVITE MODAL
    invite_modal_title: "MAAK EEN SLAPER WAKKER 🐑",
    invite_modal_username_label: "Gebruikersnaam van de slaapkop:",
    invite_modal_username_placeholder: "gebruikersnaam...",
    invite_modal_btn_confirm: "💊 RODE PIL GEVEN ▶",
    invite_modal_btn_cancel: "✕ ANNULEER",
    invite_err_not_found: "Deze slaapkop bestaat niet in de matrix.",
    invite_err_already_member: "{username} zit al in het complot.",

    // TIPS TAB
    tips_section_title: "▶ JOUW TIPS",
    tips_section_sub: "Vergrendeld bij aftrap · Knockout na 120 min",
    tips_filter_all: "ALLES",
    tips_filter_group: "GROEPSFASE",
    tips_filter_round1: "RONDE 1",
    tips_filter_round2: "RONDE 2",
    tips_filter_round3: "RONDE 3",
    tips_filter_r32: "1/32",
    tips_filter_r16: "1/16",
    tips_filter_qf: "1/4",
    tips_filter_sf: "HALVE",
    tips_filter_third: "3E PLAATS",
    tips_filter_final: "FINALE",
    tips_no_matches_in_phase: "Geen wedstrijden in deze fase.",
    tips_btn_save: "TIPS OPSLAAN ▶",
    tips_match_draw: "GELIJK",
    tips_match_locked: "🔒 VERGRENDELD",
    tips_match_after_120: "NA 120 MIN",
    tips_match_result_known: "UITSLAG BEKEND",
    tips_tooltip_draw: "= GELIJK",
    tips_phase_label_group: "GROEP",
    tips_phase_label_r32: "1/32",
    tips_phase_label_r16: "1/16",
    tips_phase_label_qf: "1/4",
    tips_phase_label_sf: "HALVE",
    tips_phase_label_third: "3E PL.",
    tips_phase_label_final: "FINALE",
    tips_match_round: "Ronde {X}",
    tips_abbrev_draw: "GLK",

    // STAND TAB
    stand_section_title: "▶ KLASSEMENT",
    stand_section_sub: "Wie neemt het meeste risico?",
    stand_filter_total: "TOTAAL",
    stand_filter_group: "🏅 POULE MEISTER",
    stand_filter_ko: "⚡ KNOCK-OUT MEISTER",
    stand_table_col_rank: "#",
    stand_table_col_player: "SPELER",
    stand_table_col_recent_tips: "RECENTE TIPS",
    stand_table_col_pts: "PTS",
    stand_stat_players: "Spelers",
    stand_stat_played: "Gespeeld",
    stand_stat_highest: "Hoogste",

    // SPELREGELS TAB
    rules_section_title: "▶ SPELREGELS",
    rules_section_sub: "No Risk, No Fun — alles wat je moet weten",
    rules_how_it_works_title: "⚽ HOE WERKT HET?",
    rules_how_it_works_body: "Tip per wedstrijd: thuisploeg wint, gelijkspel, of uitploeg wint. Geen tip ingevoerd? Dan telt automatisch gelijkspel. Tips worden vergrendeld bij aftrap — daarna kun je niet meer aanpassen. Knockoutwedstrijden: uitslag na 120 minuten (inclusief verlenging, geen penalties).",
    rules_points_title: "🎯 PUNTENSYSTEEM",
    rules_points_formula: "Punten = 100 / kans%",
    rules_points_explanation: "Hoe kleiner de kans, hoe meer punten bij een goede tip.",
    rules_points_example_fav: "Favoriet (70% kans)",
    rules_points_example_draw: "Gelijkspel (33% kans)",
    rules_points_example_underdog: "Underdog (20% kans)",
    rules_points_example_upset: "Grote verrassing (5% kans)",
    rules_standings_title: "🏅 KLASSEMENTEN",
    rules_standings_total: "Totaal — alle wedstrijden van het hele toernooi.",
    rules_standings_poule: "Poule Meister — alleen de groepsfase.",
    rules_standings_ko: "Knock-out Meister — alleen de knockoutfase.",
    rules_streaks_title: "🔥 STREAKS",
    rules_streaks_intro: "Voorspel wedstrijden op rij goed en verdien een titel. Eén foute tip en je gaat terug naar start.",
    rules_streak_threshold_label: "{X} op rij",
    rules_riskprofiles_title: "📊 RISICOPROFIELEN",
    rules_riskprofiles_intro: "Op basis van je gemiddeld gekozen kans krijg je een profiel.",
    rules_stats_title: "🎲 STATISTIEKEN",
    rules_stats_waaghals_desc: "Waaghals van de dag — degene met de laagste gemiddelde gekozen kans op een speeldag. Ongeacht goed of fout.",
    rules_stats_oddsbeater_desc: "Odds Beater — wie wint terwijl ze niet op de favoriet gokten? Hoe verder van de favoriet, hoe hoger de score.",
    rules_complot_title: "🐓 COMPLOTGROEPJES",
    rules_complot_intro: "Bouw je eigen waarheid. Ontsnap aan de matrix. Start je eigen complotgroepje en bepaal zelf wie de rode pil krijgt. De oprichter is het Haantje — de enige die weet wat er écht speelt.",
    rules_haantje_powers_label: "HAANTJE POWERS",
    rules_haantje_power_wake: "🐑 Slaper wakker maken — Geef iemand de rode pil. Hij weet nog van niets.",
    rules_haantje_power_sleep: "😴 Laten slapen — Stuur een lid terug de matrix in. Ze herinneren zich niets.",
    rules_haantje_power_crown: "🐓👑 Kronen — Geef iemand de macht over de waarheid.",
    rules_complot_haantje_note: "Een Haantje kan het complot pas verlaten als er een ander Haantje de fakkel overneemt. De waarheid moet voortbestaan.",
    rules_odds_title: "📅 ODDS & SPEELRONDES",
    rules_odds_body: "De kansen worden opgehaald via The Odds API. De admin haalt na elke speelronde de odds op voor de volgende ronde. Hoe actueler de odds, hoe eerlijker de puntenverdeling.",

    // STREAK TITLES
    streak_title_2: "🐙 PAUL",
    streak_title_4: "🌵🤠 EL JEFE",
    streak_title_6: "⚡ THE CHOSEN ONE",
    streak_title_8: "🦬 SITTING BULL",
    streak_title_10: "🕵️ THE DEEP STATE",
    streak_title_12: "🔮 THE ORACLE",
    streak_title_14: "🐙💀 PAUL WAS AN AMATEUR",
    streak_badge_label: "{emoji} {title} — {X} op rij",

    // RISK PROFILES
    risk_profile_bureaucrat_title: "De Bureaucraat",
    risk_profile_bureaucrat_sub: "Speelt alleen op papieren zekerheden. Favoriet wint? Aangevinkt.",
    risk_profile_ambtenaar_title: "De Ambtenaar",
    risk_profile_ambtenaar_sub: "Iets losser dan de bureaucraat, maar nog steeds binnen de lijntjes.",
    risk_profile_informant_title: "De Informant",
    risk_profile_informant_sub: "Heeft wat inside info, durft er iets op te gokken.",
    risk_profile_stroman_title: "De Stroman",
    risk_profile_stroman_sub: "Doet alsof hij het weet. Soms heeft ie gelijk ook.",
    risk_profile_rebel_title: "De Rebel",
    risk_profile_rebel_sub: "Trekt zich niks aan van de odds. Chaos is zijn strategie.",
    risk_profile_range_label: "{X}–{Y}% gem. kans",

    // TOERNOOI TAB
    toernooi_section_title: "▶ TOERNOOIOVERZICHT",
    toernooi_section_sub: "Groepsfase · Knockout · Standen & uitslagen",
    toernooi_filter_standings: "STANDEN",
    toernooi_filter_matches: "WEDSTRIJDEN",
    toernooi_filter_ko: "KNOCKOUT",
    toernooi_group_title: "GROEP {X}",
    toernooi_table_col_team: "Team",
    toernooi_table_col_g: "G",
    toernooi_table_col_w: "W",
    toernooi_table_col_d: "D",
    toernooi_table_col_v: "V",
    toernooi_table_col_gv: "GV",
    toernooi_table_col_gt: "GT",
    toernooi_table_col_diff: "+/-",
    toernooi_table_col_pts: "Pts",
    toernooi_no_results_yet: "Nog geen uitslagen",
    toernooi_no_group_matches: "Geen groepswedstrijden.",
    toernooi_ko_not_played: "Nog niet gespeeld",
    toernooi_ko_extended: "Verlengd",
    toernooi_no_ko_matches: "Nog geen knockoutwedstrijden.",
    toernooi_ko_vs: "VS",
    toernooi_ko_round_r32: "RONDE VAN 32",
    toernooi_ko_round_r16: "RONDE VAN 16",
    toernooi_ko_round_qf: "KWARTFINALE",
    toernooi_ko_round_sf: "HALVE FINALE",
    toernooi_ko_round_third: "3E PLAATS",
    toernooi_ko_round_final: "FINALE",

    // ADMIN TAB
    admin_section_title: "▶ ADMIN PANEEL",
    admin_section_sub: "Alleen voor de baas",
    admin_add_match_title: "⚙ WEDSTRIJD TOEVOEGEN",
    admin_label_home_team: "THUISPLOEG",
    admin_label_away_team: "UITPLOEG",
    admin_label_home_odds: "KANS THUIS %",
    admin_label_draw_odds: "KANS GELIJK %",
    admin_label_away_odds: "KANS UIT %",
    admin_label_kickoff: "AFTRAP (UTC)",
    admin_label_phase: "FASE",
    admin_phase_group: "Groepsfase",
    admin_phase_r32: "1/32 Finale",
    admin_phase_r16: "1/16 Finale",
    admin_phase_qf: "Kwartfinale",
    admin_phase_sf: "Halve Finale",
    admin_phase_third: "3e Plaats",
    admin_phase_final: "Finale",
    admin_label_group_round: "GROEP / SPEELRONDE",
    admin_round_1: "Ronde 1",
    admin_round_2: "Ronde 2",
    admin_round_3: "Ronde 3",
    admin_label_venue: "SPEELSTAD",
    admin_btn_add: "TOEVOEGEN ▶",
    admin_results_title: "✅ UITSLAG & SCORE INVOEREN",
    admin_results_no_matches: "Geen wedstrijden.",
    admin_results_placeholder_home_score: "Thuis",
    admin_results_placeholder_away_score: "Uit",
    admin_results_btn_score: "SCORE ▶",
    admin_results_btn_draw: "GELIJK",
    admin_odds_title: "📡 ODDS API",
    admin_odds_description: "Gratis account op the-odds-api.com · Key wordt opgeslagen",
    admin_odds_label_key: "API KEY",
    admin_odds_placeholder_key: "Plak je Odds API key...",
    admin_odds_label_region: "REGIO",
    admin_odds_region_eu: "Europa",
    admin_odds_region_us: "Amerika",
    admin_odds_region_uk: "VK",
    admin_odds_label_round: "SPEELRONDE (alleen groep)",
    admin_odds_btn_fetch: "ODDS OPHALEN ▶",
    admin_err_fill_teams: "Vul beide teamnamen in.",
    admin_err_fill_scores: "Vul beide scores in.",
    admin_err_no_api_key: "Vul een API-sleutel in.",
    admin_odds_loading: "Odds ophalen...",
    admin_odds_err_api_error: "API-fout {status} — controleer je key.",
    admin_odds_err_no_wc_matches: "Geen WK-wedstrijden gevonden in de API.",
    admin_odds_warn_incomplete: "⚠ Niet alle odds gevuld voor ronde {X}: {namen}",
    admin_odds_success: "✔ {X} wedstrijden bijgewerkt — ronde {Y} compleet!",
    admin_auto_odds_fetching: "Ronde {X} klaar — odds ophalen voor ronde {Y}...",

    // PROFILE MODAL
    profile_modal_btn_close: "✕ SLUITEN",
    profile_avatar_hint: "KLIK OM AVATAR TE WIJZIGEN",
    profile_section_risk_profile: "RISICO PROFIEL",
    profile_section_language: "TAAL",
    profile_avg_chosen_odds: "Gem. gekozen kans: {X}%",
    profile_section_stats: "STATISTIEKEN",
    profile_stat_points: "Punten",
    profile_stat_current_streak: "Huidige streak",
    profile_stat_longest_streak: "Langste streak",
    profile_stat_correct_played: "Goed/Gespeeld",
    profile_btn_change_avatar: "📷 AVATAR WIJZIGEN",
    profile_btn_h2h: "⚔️ HEAD-TO-HEAD",

    // HEAD-TO-HEAD MODAL
    h2h_modal_title: "⚔️ HEAD-TO-HEAD",
    h2h_modal_btn_close: "✕ SLUITEN",
    h2h_label_you: "JIJ:",
    h2h_label_opponent: "TEGENSTANDER:",
    h2h_summary_label: "SAMENVATTING · {X} WEDSTRIJD(EN)",
    h2h_result_correct_wrong: "{X} goed · {Y} fout",
    h2h_verdict_winner: "{winner} troeft {loser} genadeloos af met {diff} punten verschil.",
    h2h_verdict_draw: "{p1} en {p2} staan volledig gelijk. Nog geen winnaar.",
    h2h_no_matches: "Geen gespeelde wedstrijden.",
    h2h_not_logged_in: "Niet ingelogd.",
    h2h_filter_round1: "RONDE 1",
    h2h_filter_round2: "RONDE 2",
    h2h_filter_round3: "RONDE 3",
    h2h_filter_r32: "R32",
    h2h_filter_r16: "R16",
    h2h_filter_qf: "1/4",
    h2h_filter_sf: "HALVE",
    h2h_filter_third: "3E PLAATS",
    h2h_filter_final: "FINALE",

    // TOASTS
    toast_welcome: "Welkom {username}!",
    toast_link_copied: "Link gekopieerd!",
    toast_complot_created: "Complot {naam} aangemaakt!",
    toast_member_woke_up: "{username} is ontwaakt. Welkom in het complot.",
    toast_member_already_in: "{username} is al lid.",
    toast_member_added: "{username} toegevoegd aan het complot! 🐑",
    toast_member_kicked: "{username} slaapt weer. De matrix heeft hem terug.",
    toast_member_crowned: "👑 {USERNAME} IS NU DE WAARHEID.",
    toast_nothing_to_save: "Niets op te slaan.",
    toast_cheater: "⏰ CHEATERT! — wedstrijd is al begonnen!",
    toast_tips_saved: "✔ Tips opgeslagen!",
    toast_match_added: "Wedstrijd toegevoegd!",
    toast_score_saved: "Score & uitslag opgeslagen!",
    toast_result_saved: "Uitslag opgeslagen!",
    toast_result_cleared: "Uitslag gewist.",
    toast_avatar_saved: "Avatar opgeslagen!",
    toast_user_not_found: "Gebruiker niet gevonden.",
    toast_error_generic: "Fout: {message}",
    toast_upload_error: "Upload fout: {message}",
  },

  // ============================================================
  en: {

    // AUTH
    auth_title: "NO RISK NO FUN",
    auth_sub: "⚽ WORLD CUP POOL 2026 ⚽",
    auth_label_email: "EMAIL ADDRESS",
    auth_label_password: "PASSWORD",
    auth_label_username: "USERNAME",
    auth_placeholder_email: "your@email.com",
    auth_placeholder_password: "••••••••",
    auth_placeholder_username: "e.g. niels99",
    auth_placeholder_password_min: "min. 6 characters",
    auth_btn_login: "LOG IN ▶",
    auth_btn_register: "REGISTER ▶",
    auth_toggle_to_register: "No account? Register",
    auth_toggle_to_login: "Already have an account? Log in",
    auth_err_wrong_credentials: "✗ Wrong email or password.",
    auth_err_username_too_short: "✗ Username too short.",
    auth_err_password_too_short: "✗ Password min. 6 characters.",
    auth_err_username_taken: "✗ Username already taken.",
    auth_err_profile_not_found: "✗ Profile not found.",

    // HEADER
    header_logo_title: "NO RISK NO FUN",
    header_logo_sub: "⚽ WORLD CUP POOL 2026 ⚽",
    header_logged_in_as: "logged in as",
    header_btn_logout: "LOG OUT",

    // NAVIGATION
    nav_home: "🏠 HOME",
    nav_tips: "⚽ TIPS",
    nav_stand: "🏆 STANDINGS",
    nav_spelregels: "📖 RULES",
    nav_toernooi: "📋 TOURNAMENT",
    nav_admin: "⚙ ADMIN",

    // HOME
    home_section_title: "▶ HOME",
    home_label_podium: "YESTERDAY'S PODIUM",
    home_label_stats: "STATISTICS",
    home_label_complot: "CONSPIRACY GROUPS",
    home_loading: "Loading...",
    home_no_matches_yet: "No matches played yet.",

    // PODIUM
    podium_rank_1: "★ 1ST · CHAMPION ★",
    podium_rank_2: "2ND · SILVER",
    podium_rank_3: "3RD · BRONZE",
    podium_stat_streak: "STREAK",
    podium_stat_risk: "RISK",
    podium_stat_day_wins: "DAY WINS",
    podium_day_total: "day total",

    // STATS TICKERS
    stat_ticker_waaghals_label: "🎲 RISK TAKER OF THE DAY",
    stat_ticker_streak_label: "🔥 HOTTEST STREAK",
    stat_ticker_oddsbeater_label: "🎯 ODDS BEATER",
    stat_ticker_hint: "▶ click for full overview",
    stat_ticker_avg_chance: "avg. {X}% odds",
    stat_ticker_under_fav: "{X}% avg. below favourite",
    stats_no_data_yet: "Stats available after the first match day.",

    // STATS MODAL
    stats_modal_waaghals_title: "🎲 RISK TAKER RANKING",
    stats_modal_waaghals_sub: "Lower avg. odds = more risk taken",
    stats_modal_streaks_title: "🔥 STREAK OVERVIEW",
    stats_modal_streaks_longest: "longest: {X}",
    stats_modal_oddsbeater_title: "🎯 ODDS BEATER RANKING",
    stats_modal_oddsbeater_sub: "Wins without betting on the favourite",
    stats_modal_oddsbeater_hits: "{X}× hit · {Y} pts",
    stats_modal_no_data: "No data.",
    stats_modal_btn_close: "✕ CLOSE",

    // COMPLOT
    complot_empty_title: "YOU KNOW NOTHING",
    complot_empty_body: "You're still trapped in the matrix. Escape yourself or wait for someone to pull you out.",
    complot_btn_create: "🐓 START A CONSPIRACY",
    complot_btn_new: "+ NEW CONSPIRACY",
    complot_member_count: "{X} members",
    complot_label_ranking: "RANKINGS",
    complot_haantje_powers_label: "🐓 TOP ROOSTER POWERS",
    complot_btn_wake_up: "🐑 Wake up a sleeper",
    complot_btn_manage: "🐓 Manage conspiracy",
    complot_haantje_badge: "🐓 TOP ROOSTER",
    complot_prompt_name: "Name your conspiracy:",

    // COMPLOT MANAGE MODAL
    complot_manage_title: "MANAGE THE CONSPIRACY 🐓",
    complot_manage_invite_link_label: "INVITE LINK",
    complot_manage_btn_copy_link: "📋 COPY LINK",
    complot_manage_recruit_label: "🐑 RECRUIT A SHEEP",
    complot_manage_username_label: "Username of the sleepyhead:",
    complot_manage_username_placeholder: "username...",
    complot_manage_btn_wake_up: "💊 WAKE THEM UP",
    complot_action_btn_crown: "🐓👑 Crown",
    complot_action_btn_sleep: "😴 Put to sleep",
    complot_action_tooltip_crown: "Make this member Top Rooster too",
    complot_action_tooltip_sleep: "Send back into the matrix",
    complot_modal_btn_close: "✕ CLOSE",

    // INVITE MODAL
    invite_modal_title: "WAKE UP A SLEEPER 🐑",
    invite_modal_username_label: "Username of the sleepyhead:",
    invite_modal_username_placeholder: "username...",
    invite_modal_btn_confirm: "💊 GIVE THE RED PILL ▶",
    invite_modal_btn_cancel: "✕ CANCEL",
    invite_err_not_found: "This sleepyhead doesn't exist in the matrix.",
    invite_err_already_member: "{username} is already in the conspiracy.",

    // TIPS TAB
    tips_section_title: "▶ YOUR TIPS",
    tips_section_sub: "Locked at kick-off · Knockout after 120 min",
    tips_filter_all: "ALL",
    tips_filter_group: "GROUP STAGE",
    tips_filter_round1: "ROUND 1",
    tips_filter_round2: "ROUND 2",
    tips_filter_round3: "ROUND 3",
    tips_filter_r32: "1/32",
    tips_filter_r16: "1/16",
    tips_filter_qf: "1/4",
    tips_filter_sf: "SEMI",
    tips_filter_third: "3RD PLACE",
    tips_filter_final: "FINAL",
    tips_no_matches_in_phase: "No matches in this phase.",
    tips_btn_save: "SAVE TIPS ▶",
    tips_match_draw: "DRAW",
    tips_match_locked: "🔒 LOCKED",
    tips_match_after_120: "AFTER 120 MIN",
    tips_match_result_known: "RESULT KNOWN",
    tips_tooltip_draw: "= DRAW",
    tips_phase_label_group: "GROUP",
    tips_phase_label_r32: "1/32",
    tips_phase_label_r16: "1/16",
    tips_phase_label_qf: "1/4",
    tips_phase_label_sf: "SEMI",
    tips_phase_label_third: "3RD",
    tips_phase_label_final: "FINAL",
    tips_match_round: "Round {X}",
    tips_abbrev_draw: "DRW",

    // STAND TAB
    stand_section_title: "▶ STANDINGS",
    stand_section_sub: "Who takes the most risk?",
    stand_filter_total: "TOTAL",
    stand_filter_group: "🏅 POULE MEISTER",
    stand_filter_ko: "⚡ KNOCK-OUT MEISTER",
    stand_table_col_rank: "#",
    stand_table_col_player: "PLAYER",
    stand_table_col_recent_tips: "RECENT TIPS",
    stand_table_col_pts: "PTS",
    stand_stat_players: "Players",
    stand_stat_played: "Played",
    stand_stat_highest: "Highest",

    // SPELREGELS TAB
    rules_section_title: "▶ RULES",
    rules_section_sub: "No Risk, No Fun — everything you need to know",
    rules_how_it_works_title: "⚽ HOW DOES IT WORK?",
    rules_how_it_works_body: "Tip per match: home team wins, draw, or away team wins. No tip entered? Draw counts automatically. Tips are locked at kick-off — no changes after that. Knockout matches: result after 120 minutes (including extra time, no penalties).",
    rules_points_title: "🎯 POINTS SYSTEM",
    rules_points_formula: "Points = 100 / odds%",
    rules_points_explanation: "The lower the odds, the more points for a correct tip.",
    rules_points_example_fav: "Favourite (70% odds)",
    rules_points_example_draw: "Draw (33% odds)",
    rules_points_example_underdog: "Underdog (20% odds)",
    rules_points_example_upset: "Major upset (5% odds)",
    rules_standings_title: "🏅 STANDINGS",
    rules_standings_total: "Total — all matches of the entire tournament.",
    rules_standings_poule: "Poule Meister — group stage only.",
    rules_standings_ko: "Knock-out Meister — knockout stage only.",
    rules_streaks_title: "🔥 STREAKS",
    rules_streaks_intro: "Predict matches correctly in a row and earn a title. One wrong tip and you're back to zero.",
    rules_streak_threshold_label: "{X} in a row",
    rules_riskprofiles_title: "📊 RISK PROFILES",
    rules_riskprofiles_intro: "Based on your average chosen odds you get assigned a profile.",
    rules_stats_title: "🎲 STATISTICS",
    rules_stats_waaghals_desc: "Risk taker of the day — the one with the lowest average chosen odds on a match day. Regardless of correct or wrong.",
    rules_stats_oddsbeater_desc: "Odds Beater — who wins without betting on the favourite? The further from the favourite, the higher the score.",
    rules_complot_title: "🐓 CONSPIRACY GROUPS",
    rules_complot_intro: "Build your own truth. Escape the matrix. Start your own conspiracy group and decide who gets the red pill. The founder is the Top Rooster — the only one who knows what's really going on.",
    rules_haantje_powers_label: "TOP ROOSTER POWERS",
    rules_haantje_power_wake: "🐑 Wake up a sleeper — Give someone the red pill. They have no idea yet.",
    rules_haantje_power_sleep: "😴 Put to sleep — Send a member back into the matrix. They'll remember nothing.",
    rules_haantje_power_crown: "🐓👑 Crown — Hand someone the power over the truth.",
    rules_complot_haantje_note: "A Top Rooster can only leave the conspiracy once another Top Rooster takes over. The truth must live on.",
    rules_odds_title: "📅 ODDS & MATCH ROUNDS",
    rules_odds_body: "Odds are fetched via The Odds API. The admin fetches the odds after each round for the next one. The more up to date the odds, the fairer the points distribution.",

    // STREAK TITLES (same in all languages)
    streak_title_2: "🐙 PAUL",
    streak_title_4: "🌵🤠 EL JEFE",
    streak_title_6: "⚡ THE CHOSEN ONE",
    streak_title_8: "🦬 SITTING BULL",
    streak_title_10: "🕵️ THE DEEP STATE",
    streak_title_12: "🔮 THE ORACLE",
    streak_title_14: "🐙💀 PAUL WAS AN AMATEUR",
    streak_badge_label: "{emoji} {title} — {X} in a row",

    // RISK PROFILES
    risk_profile_bureaucrat_title: "The Bureaucrat",
    risk_profile_bureaucrat_sub: "Only plays the sure thing on paper. Favourite wins? Ticked off.",
    risk_profile_ambtenaar_title: "The Civil Servant",
    risk_profile_ambtenaar_sub: "Slightly looser than the bureaucrat, but still colours within the lines.",
    risk_profile_informant_title: "The Informant",
    risk_profile_informant_sub: "Has some inside info, dares to act on it.",
    risk_profile_stroman_title: "The Front Man",
    risk_profile_stroman_sub: "Acts like he knows. Sometimes he's actually right.",
    risk_profile_rebel_title: "The Rebel",
    risk_profile_rebel_sub: "Couldn't care less about the odds. Chaos is his strategy.",
    risk_profile_range_label: "{X}–{Y}% avg. odds",

    // TOERNOOI TAB
    toernooi_section_title: "▶ TOURNAMENT OVERVIEW",
    toernooi_section_sub: "Group stage · Knockout · Standings & results",
    toernooi_filter_standings: "STANDINGS",
    toernooi_filter_matches: "MATCHES",
    toernooi_filter_ko: "KNOCKOUT",
    toernooi_group_title: "GROUP {X}",
    toernooi_table_col_team: "Team",
    toernooi_table_col_g: "P",
    toernooi_table_col_w: "W",
    toernooi_table_col_d: "D",
    toernooi_table_col_v: "L",
    toernooi_table_col_gv: "GF",
    toernooi_table_col_gt: "GA",
    toernooi_table_col_diff: "+/-",
    toernooi_table_col_pts: "Pts",
    toernooi_no_results_yet: "No results yet",
    toernooi_no_group_matches: "No group matches.",
    toernooi_ko_not_played: "Not played yet",
    toernooi_ko_extended: "Extra time",
    toernooi_no_ko_matches: "No knockout matches yet.",
    toernooi_ko_vs: "VS",
    toernooi_ko_round_r32: "ROUND OF 32",
    toernooi_ko_round_r16: "ROUND OF 16",
    toernooi_ko_round_qf: "QUARTER FINAL",
    toernooi_ko_round_sf: "SEMI FINAL",
    toernooi_ko_round_third: "3RD PLACE",
    toernooi_ko_round_final: "FINAL",

    // ADMIN TAB
    admin_section_title: "▶ ADMIN PANEL",
    admin_section_sub: "For the boss only",
    admin_add_match_title: "⚙ ADD MATCH",
    admin_label_home_team: "HOME TEAM",
    admin_label_away_team: "AWAY TEAM",
    admin_label_home_odds: "HOME ODDS %",
    admin_label_draw_odds: "DRAW ODDS %",
    admin_label_away_odds: "AWAY ODDS %",
    admin_label_kickoff: "KICK-OFF (UTC)",
    admin_label_phase: "PHASE",
    admin_phase_group: "Group Stage",
    admin_phase_r32: "Round of 32",
    admin_phase_r16: "Round of 16",
    admin_phase_qf: "Quarter Final",
    admin_phase_sf: "Semi Final",
    admin_phase_third: "3rd Place",
    admin_phase_final: "Final",
    admin_label_group_round: "GROUP / ROUND",
    admin_round_1: "Round 1",
    admin_round_2: "Round 2",
    admin_round_3: "Round 3",
    admin_label_venue: "VENUE",
    admin_btn_add: "ADD ▶",
    admin_results_title: "✅ ENTER RESULT & SCORE",
    admin_results_no_matches: "No matches.",
    admin_results_placeholder_home_score: "Home",
    admin_results_placeholder_away_score: "Away",
    admin_results_btn_score: "SCORE ▶",
    admin_results_btn_draw: "DRAW",
    admin_odds_title: "📡 ODDS API",
    admin_odds_description: "Free account at the-odds-api.com · Key is saved",
    admin_odds_label_key: "API KEY",
    admin_odds_placeholder_key: "Paste your Odds API key...",
    admin_odds_label_region: "REGION",
    admin_odds_region_eu: "Europe",
    admin_odds_region_us: "Americas",
    admin_odds_region_uk: "UK",
    admin_odds_label_round: "ROUND (group stage only)",
    admin_odds_btn_fetch: "FETCH ODDS ▶",
    admin_err_fill_teams: "Fill in both team names.",
    admin_err_fill_scores: "Fill in both scores.",
    admin_err_no_api_key: "Enter an API key.",
    admin_odds_loading: "Fetching odds...",
    admin_odds_err_api_error: "API error {status} — check your key.",
    admin_odds_err_no_wc_matches: "No World Cup matches found in the API.",
    admin_odds_warn_incomplete: "⚠ Not all odds filled for round {X}: {namen}",
    admin_odds_success: "✔ {X} matches updated — round {Y} complete!",
    admin_auto_odds_fetching: "Round {X} done — fetching odds for round {Y}...",

    // PROFILE MODAL
    profile_modal_btn_close: "✕ CLOSE",
    profile_avatar_hint: "CLICK TO CHANGE AVATAR",
    profile_section_risk_profile: "RISK PROFILE",
    profile_section_language: "LANGUAGE",
    profile_avg_chosen_odds: "Avg. chosen odds: {X}%",
    profile_section_stats: "STATISTICS",
    profile_stat_points: "Points",
    profile_stat_current_streak: "Current streak",
    profile_stat_longest_streak: "Longest streak",
    profile_stat_correct_played: "Correct/Played",
    profile_btn_change_avatar: "📷 CHANGE AVATAR",
    profile_btn_h2h: "⚔️ HEAD-TO-HEAD",

    // HEAD-TO-HEAD MODAL
    h2h_modal_title: "⚔️ HEAD-TO-HEAD",
    h2h_modal_btn_close: "✕ CLOSE",
    h2h_label_you: "YOU:",
    h2h_label_opponent: "OPPONENT:",
    h2h_summary_label: "SUMMARY · {X} MATCH(ES)",
    h2h_result_correct_wrong: "{X} correct · {Y} wrong",
    h2h_verdict_winner: "{winner} mercilessly crushes {loser} by {diff} points.",
    h2h_verdict_draw: "{p1} and {p2} are completely even. No winner yet.",
    h2h_no_matches: "No matches played.",
    h2h_not_logged_in: "Not logged in.",
    h2h_filter_round1: "ROUND 1",
    h2h_filter_round2: "ROUND 2",
    h2h_filter_round3: "ROUND 3",
    h2h_filter_r32: "R32",
    h2h_filter_r16: "R16",
    h2h_filter_qf: "1/4",
    h2h_filter_sf: "SEMI",
    h2h_filter_third: "3RD PLACE",
    h2h_filter_final: "FINAL",

    // TOASTS
    toast_welcome: "Welcome {username}!",
    toast_link_copied: "Link copied!",
    toast_complot_created: "Conspiracy {naam} created!",
    toast_member_woke_up: "{username} has awakened. Welcome to the conspiracy.",
    toast_member_already_in: "{username} is already a member.",
    toast_member_added: "{username} added to the conspiracy! 🐑",
    toast_member_kicked: "{username} is asleep again. The matrix has reclaimed them.",
    toast_member_crowned: "👑 {USERNAME} IS NOW THE TRUTH.",
    toast_nothing_to_save: "Nothing to save.",
    toast_cheater: "⏰ CHEATER! — match has already started!",
    toast_tips_saved: "✔ Tips saved!",
    toast_match_added: "Match added!",
    toast_score_saved: "Score & result saved!",
    toast_result_saved: "Result saved!",
    toast_result_cleared: "Result cleared.",
    toast_avatar_saved: "Avatar saved!",
    toast_user_not_found: "User not found.",
    toast_error_generic: "Error: {message}",
    toast_upload_error: "Upload error: {message}",
  },

  // ============================================================
  de: {

    // AUTH
    auth_title: "NO RISK NO FUN",
    auth_sub: "⚽ WM POOL 2026 ⚽",
    auth_label_email: "E-MAIL-ADRESSE",
    auth_label_password: "PASSWORT",
    auth_label_username: "BENUTZERNAME",
    auth_placeholder_email: "deine@email.de",
    auth_placeholder_password: "••••••••",
    auth_placeholder_username: "z.B. niels99",
    auth_placeholder_password_min: "mind. 6 Zeichen",
    auth_btn_login: "ANMELDEN ▶",
    auth_btn_register: "REGISTRIEREN ▶",
    auth_toggle_to_register: "Kein Konto? Registrieren",
    auth_toggle_to_login: "Schon ein Konto? Anmelden",
    auth_err_wrong_credentials: "✗ Falsche E-Mail oder Passwort.",
    auth_err_username_too_short: "✗ Benutzername zu kurz.",
    auth_err_password_too_short: "✗ Passwort mind. 6 Zeichen.",
    auth_err_username_taken: "✗ Benutzername bereits vergeben.",
    auth_err_profile_not_found: "✗ Profil nicht gefunden.",

    // HEADER
    header_logo_title: "NO RISK NO FUN",
    header_logo_sub: "⚽ WM POOL 2026 ⚽",
    header_logged_in_as: "angemeldet als",
    header_btn_logout: "ABMELDEN",

    // NAVIGATION
    nav_home: "🏠 HOME",
    nav_tips: "⚽ TIPS",
    nav_stand: "🏆 TABELLE",
    nav_spelregels: "📖 REGELN",
    nav_toernooi: "📋 TURNIER",
    nav_admin: "⚙ ADMIN",

    // HOME
    home_section_title: "▶ HOME",
    home_label_podium: "PODIUM GESTERN",
    home_label_stats: "STATISTIKEN",
    home_label_complot: "KOMPLOTTGRUPPEN",
    home_loading: "Laden...",
    home_no_matches_yet: "Noch keine Spiele gespielt.",

    // PODIUM
    podium_rank_1: "★ 1ST · CHAMPION ★",
    podium_rank_2: "2ND · SILVER",
    podium_rank_3: "3RD · BRONZE",
    podium_stat_streak: "STREAK",
    podium_stat_risk: "RISIKO",
    podium_stat_day_wins: "TAGESSIEGE",
    podium_day_total: "Tagessumme",

    // STATS TICKERS
    stat_ticker_waaghals_label: "🎲 DRAUFGÄNGER DES TAGES",
    stat_ticker_streak_label: "🔥 HEISSESTE STREAK",
    stat_ticker_oddsbeater_label: "🎯 ODDS BEATER",
    stat_ticker_hint: "▶ klick für vollständige Übersicht",
    stat_ticker_avg_chance: "Ø {X}% Chance",
    stat_ticker_under_fav: "{X}% Ø unter Favorit",
    stats_no_data_yet: "Stats verfügbar nach dem ersten Spieltag.",

    // STATS MODAL
    stats_modal_waaghals_title: "🎲 DRAUFGÄNGER RANKING",
    stats_modal_waaghals_sub: "Niedrigere Ø Chance = mehr Risiko",
    stats_modal_streaks_title: "🔥 STREAK ÜBERSICHT",
    stats_modal_streaks_longest: "längste: {X}",
    stats_modal_oddsbeater_title: "🎯 ODDS BEATER RANKING",
    stats_modal_oddsbeater_sub: "Gewinnt ohne auf den Favoriten zu tippen",
    stats_modal_oddsbeater_hits: "{X}× Treffer · {Y} Pkt",
    stats_modal_no_data: "Keine Daten.",
    stats_modal_btn_close: "✕ SCHLIESSEN",

    // COMPLOT
    complot_empty_title: "DU WEISST NOCH NICHTS",
    complot_empty_body: "Du steckst noch in der Matrix. Entkomm selbst oder warte, bis jemand dich rausholt.",
    complot_btn_create: "🐓 KOMPLOTT GRÜNDEN",
    complot_btn_new: "+ NEUES KOMPLOTT",
    complot_member_count: "{X} Mitglieder",
    complot_label_ranking: "RANGLISTE",
    complot_haantje_powers_label: "🐓 HAHN POWERS",
    complot_btn_wake_up: "🐑 Schläfer aufwecken",
    complot_btn_manage: "🐓 Komplott verwalten",
    complot_haantje_badge: "🐓 DER HAHN",
    complot_prompt_name: "Name deines Komplotts:",

    // COMPLOT MANAGE MODAL
    complot_manage_title: "KOMPLOTT VERWALTEN 🐓",
    complot_manage_invite_link_label: "EINLADUNGSLINK",
    complot_manage_btn_copy_link: "📋 LINK KOPIEREN",
    complot_manage_recruit_label: "🐑 SCHAF REKRUTIEREN",
    complot_manage_username_label: "Benutzername des Schlafkopfs:",
    complot_manage_username_placeholder: "Benutzername...",
    complot_manage_btn_wake_up: "💊 AUFWECKEN",
    complot_action_btn_crown: "🐓👑 Krönen",
    complot_action_btn_sleep: "😴 Schlafen lassen",
    complot_action_tooltip_crown: "Dieses Mitglied zum Hahn machen",
    complot_action_tooltip_sleep: "Zurück in die Matrix schicken",
    complot_modal_btn_close: "✕ SCHLIESSEN",

    // INVITE MODAL
    invite_modal_title: "WECKE EINEN SCHLÄFER 🐑",
    invite_modal_username_label: "Benutzername des Schlafkopfs:",
    invite_modal_username_placeholder: "Benutzername...",
    invite_modal_btn_confirm: "💊 ROTE PILLE GEBEN ▶",
    invite_modal_btn_cancel: "✕ ABBRECHEN",
    invite_err_not_found: "Dieser Schlafkopf existiert nicht in der Matrix.",
    invite_err_already_member: "{username} ist bereits im Komplott.",

    // TIPS TAB
    tips_section_title: "▶ DEINE TIPS",
    tips_section_sub: "Gesperrt bei Anpfiff · Knockout nach 120 Min",
    tips_filter_all: "ALLES",
    tips_filter_group: "GRUPPENPHASE",
    tips_filter_round1: "RUNDE 1",
    tips_filter_round2: "RUNDE 2",
    tips_filter_round3: "RUNDE 3",
    tips_filter_r32: "1/32",
    tips_filter_r16: "1/16",
    tips_filter_qf: "1/4",
    tips_filter_sf: "HALBFINALE",
    tips_filter_third: "3. PLATZ",
    tips_filter_final: "FINALE",
    tips_no_matches_in_phase: "Keine Spiele in dieser Phase.",
    tips_btn_save: "TIPPS SPEICHERN ▶",
    tips_match_draw: "UNENT.",
    tips_match_locked: "🔒 GESPERRT",
    tips_match_after_120: "NACH 120 MIN",
    tips_match_result_known: "ERGEBNIS BEKANNT",
    tips_tooltip_draw: "= UNENTSCHIEDEN",
    tips_phase_label_group: "GRUPPE",
    tips_phase_label_r32: "1/32",
    tips_phase_label_r16: "1/16",
    tips_phase_label_qf: "1/4",
    tips_phase_label_sf: "HALB",
    tips_phase_label_third: "3. PL.",
    tips_phase_label_final: "FINALE",
    tips_match_round: "Runde {X}",
    tips_abbrev_draw: "UNE",

    // STAND TAB
    stand_section_title: "▶ RANGLISTE",
    stand_section_sub: "Wer geht das meiste Risiko ein?",
    stand_filter_total: "GESAMT",
    stand_filter_group: "🏅 POULE MEISTER",
    stand_filter_ko: "⚡ KNOCK-OUT MEISTER",
    stand_table_col_rank: "#",
    stand_table_col_player: "SPIELER",
    stand_table_col_recent_tips: "LETZTE TIPS",
    stand_table_col_pts: "PKT",
    stand_stat_players: "Spieler",
    stand_stat_played: "Gespielt",
    stand_stat_highest: "Höchste",

    // SPELREGELS TAB
    rules_section_title: "▶ REGELN",
    rules_section_sub: "No Risk, No Fun — alles was du wissen musst",
    rules_how_it_works_title: "⚽ WIE FUNKTIONIERT ES?",
    rules_how_it_works_body: "Tipp pro Spiel: Heimteam gewinnt, Unentschieden oder Auswärtsteam gewinnt. Kein Tipp eingegeben? Unentschieden zählt automatisch. Tipps werden beim Anpfiff gesperrt — danach keine Änderungen mehr. Knockout-Spiele: Ergebnis nach 120 Minuten (inkl. Verlängerung, keine Elfmeter).",
    rules_points_title: "🎯 PUNKTESYSTEM",
    rules_points_formula: "Punkte = 100 / Chance%",
    rules_points_explanation: "Je niedriger die Chance, desto mehr Punkte bei einem richtigen Tipp.",
    rules_points_example_fav: "Favorit (70% Chance)",
    rules_points_example_draw: "Unentschieden (33% Chance)",
    rules_points_example_underdog: "Underdog (20% Chance)",
    rules_points_example_upset: "Große Überraschung (5% Chance)",
    rules_standings_title: "🏅 RANGLISTEN",
    rules_standings_total: "Gesamt — alle Spiele des gesamten Turniers.",
    rules_standings_poule: "Poule Meister — nur die Gruppenphase.",
    rules_standings_ko: "Knock-out Meister — nur die Knockoutphase.",
    rules_streaks_title: "🔥 STREAKS",
    rules_streaks_intro: "Sag Spiele hintereinander richtig voraus und verdiene einen Titel. Ein falscher Tipp und du fängst von vorne an.",
    rules_streak_threshold_label: "{X} hintereinander",
    rules_riskprofiles_title: "📊 RISIKOPROFILE",
    rules_riskprofiles_intro: "Basierend auf deiner durchschnittlich gewählten Chance erhältst du ein Profil.",
    rules_stats_title: "🎲 STATISTIKEN",
    rules_stats_waaghals_desc: "Draufgänger des Tages — derjenige mit der niedrigsten durchschnittlich gewählten Chance an einem Spieltag. Egal ob richtig oder falsch.",
    rules_stats_oddsbeater_desc: "Odds Beater — wer gewinnt ohne auf den Favoriten zu tippen? Je weiter vom Favoriten entfernt, desto höher die Punktzahl.",
    rules_complot_title: "🐓 KOMPLOTTGRUPPEN",
    rules_complot_intro: "Baue deine eigene Wahrheit. Entkomm der Matrix. Starte deine eigene Komplottgruppe und entscheide selbst, wer die rote Pille bekommt. Der Gründer ist der Hahn — der Einzige, der weiß, was wirklich gespielt wird.",
    rules_haantje_powers_label: "HAHN POWERS",
    rules_haantje_power_wake: "🐑 Schläfer aufwecken — Gib jemandem die rote Pille. Er ahnt noch nichts.",
    rules_haantje_power_sleep: "😴 Schlafen lassen — Schick ein Mitglied zurück in die Matrix. Sie erinnern sich an nichts.",
    rules_haantje_power_crown: "🐓👑 Krönen — Gib jemandem die Macht über die Wahrheit.",
    rules_complot_haantje_note: "Ein Hahn kann das Komplott erst verlassen, wenn ein anderer Hahn die Fackel übernimmt. Die Wahrheit muss weiterleben.",
    rules_odds_title: "📅 QUOTEN & SPIELRUNDEN",
    rules_odds_body: "Die Quoten werden über The Odds API abgerufen. Der Admin holt nach jeder Runde die Quoten für die nächste. Je aktueller die Quoten, desto fairer die Punkteverteilung.",

    // STREAK TITLES (same in all languages)
    streak_title_2: "🐙 PAUL",
    streak_title_4: "🌵🤠 EL JEFE",
    streak_title_6: "⚡ THE CHOSEN ONE",
    streak_title_8: "🦬 SITTING BULL",
    streak_title_10: "🕵️ THE DEEP STATE",
    streak_title_12: "🔮 THE ORACLE",
    streak_title_14: "🐙💀 PAUL WAS AN AMATEUR",
    streak_badge_label: "{emoji} {title} — {X} hintereinander",

    // RISK PROFILES
    risk_profile_bureaucrat_title: "Der Bürokrat",
    risk_profile_bureaucrat_sub: "Spielt nur auf sichere Papierwerte. Favorit gewinnt? Abgehakt.",
    risk_profile_ambtenaar_title: "Der Beamte",
    risk_profile_ambtenaar_sub: "Etwas lockerer als der Bürokrat, aber immer noch innerhalb der Grenzen.",
    risk_profile_informant_title: "Der Informant",
    risk_profile_informant_sub: "Hat ein paar Insiderinfos und wagt es, darauf zu setzen.",
    risk_profile_stroman_title: "Der Strohmann",
    risk_profile_stroman_sub: "Tut so als ob er es weiß. Manchmal hat er sogar recht.",
    risk_profile_rebel_title: "Der Rebell",
    risk_profile_rebel_sub: "Schert sich nicht um die Quoten. Chaos ist seine Strategie.",
    risk_profile_range_label: "{X}–{Y}% Ø Chance",

    // TOERNOOI TAB
    toernooi_section_title: "▶ TURNIERÜBERSICHT",
    toernooi_section_sub: "Gruppenphase · Knockout · Tabellen & Ergebnisse",
    toernooi_filter_standings: "TABELLEN",
    toernooi_filter_matches: "SPIELE",
    toernooi_filter_ko: "KNOCKOUT",
    toernooi_group_title: "GRUPPE {X}",
    toernooi_table_col_team: "Team",
    toernooi_table_col_g: "Sp",
    toernooi_table_col_w: "S",
    toernooi_table_col_d: "U",
    toernooi_table_col_v: "N",
    toernooi_table_col_gv: "Tf",
    toernooi_table_col_gt: "Tg",
    toernooi_table_col_diff: "+/-",
    toernooi_table_col_pts: "Pkt",
    toernooi_no_results_yet: "Noch keine Ergebnisse",
    toernooi_no_group_matches: "Keine Gruppenspiele.",
    toernooi_ko_not_played: "Noch nicht gespielt",
    toernooi_ko_extended: "Verlängerung",
    toernooi_no_ko_matches: "Noch keine Knockout-Spiele.",
    toernooi_ko_vs: "VS",
    toernooi_ko_round_r32: "RUNDE DER 32",
    toernooi_ko_round_r16: "RUNDE DER 16",
    toernooi_ko_round_qf: "VIERTELFINALE",
    toernooi_ko_round_sf: "HALBFINALE",
    toernooi_ko_round_third: "3. PLATZ",
    toernooi_ko_round_final: "FINALE",

    // ADMIN TAB
    admin_section_title: "▶ ADMIN PANEL",
    admin_section_sub: "Nur für den Chef",
    admin_add_match_title: "⚙ SPIEL HINZUFÜGEN",
    admin_label_home_team: "HEIMTEAM",
    admin_label_away_team: "AUSWÄRTSTEAM",
    admin_label_home_odds: "HEIM CHANCE %",
    admin_label_draw_odds: "UNENTSCHIEDEN %",
    admin_label_away_odds: "AUSWÄRTS CHANCE %",
    admin_label_kickoff: "ANPFIFF (UTC)",
    admin_label_phase: "PHASE",
    admin_phase_group: "Gruppenphase",
    admin_phase_r32: "Runde der 32",
    admin_phase_r16: "Runde der 16",
    admin_phase_qf: "Viertelfinale",
    admin_phase_sf: "Halbfinale",
    admin_phase_third: "3. Platz",
    admin_phase_final: "Finale",
    admin_label_group_round: "GRUPPE / RUNDE",
    admin_round_1: "Runde 1",
    admin_round_2: "Runde 2",
    admin_round_3: "Runde 3",
    admin_label_venue: "SPIELORT",
    admin_btn_add: "HINZUFÜGEN ▶",
    admin_results_title: "✅ ERGEBNIS & SCORE EINGEBEN",
    admin_results_no_matches: "Keine Spiele.",
    admin_results_placeholder_home_score: "Heim",
    admin_results_placeholder_away_score: "Auswärts",
    admin_results_btn_score: "SCORE ▶",
    admin_results_btn_draw: "UNENTSCHIEDEN",
    admin_odds_title: "📡 ODDS API",
    admin_odds_description: "Kostenloses Konto auf the-odds-api.com · Key wird gespeichert",
    admin_odds_label_key: "API KEY",
    admin_odds_placeholder_key: "Füge deinen Odds API Key ein...",
    admin_odds_label_region: "REGION",
    admin_odds_region_eu: "Europa",
    admin_odds_region_us: "Amerika",
    admin_odds_region_uk: "UK",
    admin_odds_label_round: "RUNDE (nur Gruppenphase)",
    admin_odds_btn_fetch: "QUOTEN ABRUFEN ▶",
    admin_err_fill_teams: "Fülle beide Teamnamen aus.",
    admin_err_fill_scores: "Fülle beide Ergebnisse aus.",
    admin_err_no_api_key: "Gib einen API-Schlüssel ein.",
    admin_odds_loading: "Quoten abrufen...",
    admin_odds_err_api_error: "API-Fehler {status} — überprüfe deinen Key.",
    admin_odds_err_no_wc_matches: "Keine WM-Spiele in der API gefunden.",
    admin_odds_warn_incomplete: "⚠ Nicht alle Quoten für Runde {X} gefüllt: {namen}",
    admin_odds_success: "✔ {X} Spiele aktualisiert — Runde {Y} komplett!",
    admin_auto_odds_fetching: "Runde {X} fertig — Quoten für Runde {Y} abrufen...",

    // PROFILE MODAL
    profile_modal_btn_close: "✕ SCHLIESSEN",
    profile_avatar_hint: "KLICKEN UM AVATAR ZU ÄNDERN",
    profile_section_risk_profile: "RISIKOPROFIL",
    profile_section_language: "SPRACHE",
    profile_avg_chosen_odds: "Ø gewählte Chance: {X}%",
    profile_section_stats: "STATISTIKEN",
    profile_stat_points: "Punkte",
    profile_stat_current_streak: "Aktuelle Streak",
    profile_stat_longest_streak: "Längste Streak",
    profile_stat_correct_played: "Richtig/Gespielt",
    profile_btn_change_avatar: "📷 AVATAR ÄNDERN",
    profile_btn_h2h: "⚔️ HEAD-TO-HEAD",

    // HEAD-TO-HEAD MODAL
    h2h_modal_title: "⚔️ HEAD-TO-HEAD",
    h2h_modal_btn_close: "✕ SCHLIESSEN",
    h2h_label_you: "DU:",
    h2h_label_opponent: "GEGNER:",
    h2h_summary_label: "ZUSAMMENFASSUNG · {X} SPIEL(E)",
    h2h_result_correct_wrong: "{X} richtig · {Y} falsch",
    h2h_verdict_winner: "{winner} schlägt {loser} gnadenlos mit {diff} Punkten Vorsprung.",
    h2h_verdict_draw: "{p1} und {p2} sind völlig gleichauf. Noch kein Gewinner.",
    h2h_no_matches: "Keine Spiele gespielt.",
    h2h_not_logged_in: "Nicht angemeldet.",
    h2h_filter_round1: "RUNDE 1",
    h2h_filter_round2: "RUNDE 2",
    h2h_filter_round3: "RUNDE 3",
    h2h_filter_r32: "R32",
    h2h_filter_r16: "R16",
    h2h_filter_qf: "1/4",
    h2h_filter_sf: "HALB",
    h2h_filter_third: "3. PLATZ",
    h2h_filter_final: "FINALE",

    // TOASTS
    toast_welcome: "Willkommen {username}!",
    toast_link_copied: "Link kopiert!",
    toast_complot_created: "Komplott {naam} gegründet!",
    toast_member_woke_up: "{username} ist erwacht. Willkommen im Komplott.",
    toast_member_already_in: "{username} ist bereits Mitglied.",
    toast_member_added: "{username} zum Komplott hinzugefügt! 🐑",
    toast_member_kicked: "{username} schläft wieder. Die Matrix hat ihn zurück.",
    toast_member_crowned: "👑 {USERNAME} IST JETZT DIE WAHRHEIT.",
    toast_nothing_to_save: "Nichts zu speichern.",
    toast_cheater: "⏰ CHEATER! — Spiel hat bereits begonnen!",
    toast_tips_saved: "✔ Tipps gespeichert!",
    toast_match_added: "Spiel hinzugefügt!",
    toast_score_saved: "Score & Ergebnis gespeichert!",
    toast_result_saved: "Ergebnis gespeichert!",
    toast_result_cleared: "Ergebnis gelöscht.",
    toast_avatar_saved: "Avatar gespeichert!",
    toast_user_not_found: "Benutzer nicht gefunden.",
    toast_error_generic: "Fehler: {message}",
    toast_upload_error: "Upload-Fehler: {message}",
  }
};

// ============================================================
// HELPER FUNCTIONS
// ============================================================

// Current language — loaded from localStorage, fallback to 'nl'
let _currentLang = localStorage.getItem('nrnf_lang') || 'nl';

// Get current language code
function getCurrentLanguage() {
  return _currentLang;
}

// Translate a key, with optional variable replacements
// Usage: t('toast_welcome', { username: 'Niels' })
function t(key, vars = {}) {
  const lang = TRANSLATIONS[_currentLang] || TRANSLATIONS['nl'];
  let str = lang[key] ?? TRANSLATIONS['nl'][key] ?? key;
  for (const [k, v] of Object.entries(vars)) {
    str = str.replaceAll(`{${k}}`, v);
  }
  return str;
}

// Set language in memory + localStorage
function setLanguage(lang) {
  if (!TRANSLATIONS[lang]) return;
  _currentLang = lang;
  localStorage.setItem('nrnf_lang', lang);
}

// Save language preference to Supabase profiles table
async function saveLanguageToProfile(userId, lang, sb) {
  if (!userId || !TRANSLATIONS[lang] || !sb) return;
  await sb
    .from('profiles')
    .update({ language: lang })
    .eq('id', userId);
}

// Load language preference from Supabase and apply it
async function loadLanguageFromProfile(userId, sb) {
  if (!userId || !sb) return;
  const { data } = await sb
    .from('profiles')
    .select('language')
    .eq('id', userId)
    .single();
  if (data?.language && TRANSLATIONS[data.language]) {
    setLanguage(data.language);
  }
}
const TEAM_NAMES = {
  en: {}, // Engels blijft zoals het is uit de Odds API
  nl: {
    // Noord- & Midden-Amerika
    'United States':       'Verenigde Staten',
    'USA':                 'VS',
    'Mexico':              'Mexico',
    'Canada':              'Canada',
    'Honduras':            'Honduras',
    'Panama':              'Panama',
    'Costa Rica':          'Costa Rica',
    'Jamaica':             'Jamaica',
    'El Salvador':         'El Salvador',
    'Haiti':               'Haïti',
    'Curacao':             'Curaçao',

    // Zuid-Amerika
    'Brazil':              'Brazilië',
    'Argentina':           'Argentinië',
    'Colombia':            'Colombia',
    'Uruguay':             'Uruguay',
    'Ecuador':             'Ecuador',
    'Chile':               'Chili',
    'Venezuela':           'Venezuela',
    'Bolivia':             'Bolivia',
    'Paraguay':            'Paraguay',
    'Peru':                'Peru',

    // Europa
    'Germany':             'Duitsland',
    'France':              'Frankrijk',
    'Spain':               'Spanje',
    'England':             'Engeland',
    'Netherlands':         'Nederland',
    'Portugal':            'Portugal',
    'Belgium':             'België',
    'Italy':               'Italië',
    'Croatia':             'Kroatië',
    'Serbia':              'Servië',
    'Austria':             'Oostenrijk',
    'Switzerland':         'Zwitserland',
    'Denmark':             'Denemarken',
    'Poland':              'Polen',
    'Ukraine':             'Oekraïne',
    'Scotland':            'Schotland',
    'Turkey':              'Turkije',
    'Hungary':             'Hongarije',
    'Romania':             'Roemenië',
    'Czech Republic':      'Tsjechië',
    'Slovakia':            'Slowakije',
    'Greece':              'Griekenland',
    'Norway':              'Noorwegen',
    'Sweden':              'Zweden',
    'Finland':             'Finland',
    'Slovenia':            'Slovenië',
    'Albania':             'Albanië',
    'Georgia':             'Georgië',
    'Bosnia':              'Bosnië',

    // Afrika
    'Morocco':             'Marokko',
    'Senegal':             'Senegal',
    'Egypt':               'Egypte',
    'Nigeria':             'Nigeria',
    'Cameroon':            'Kameroen',
    'Ghana':               'Ghana',
    'Ivory Coast':         'Ivoorkust',
    'Mali':                'Mali',
    'Algeria':             'Algerije',
    'Tunisia':             'Tunesië',
    'South Africa':        'Zuid-Afrika',
    'DR Congo':            'DR Congo',
    'Cape Verde':          'Kaapverdië',
    'Zambia':              'Zambia',
    'Tanzania':            'Tanzania',
    'Angola':              'Angola',

    // Azië & Oceanië
    'Japan':               'Japan',
    'South Korea':         'Zuid-Korea',
    'Iran':                'Iran',
    'Saudi Arabia':        'Saoedi-Arabië',
    'Australia':           'Australië',
    'Qatar':               'Qatar',
    'Iraq':                'Irak',
    'Uzbekistan':          'Oezbekistan',
    'Jordan':              'Jordanië',
    'Oman':                'Oman',
    'New Zealand':         'Nieuw-Zeeland',
  },
  de: {
    // Noord- & Midden-Amerika
    'United States':       'USA',
    'USA':                 'USA',
    'Mexico':              'Mexiko',
    'Canada':              'Kanada',
    'Honduras':            'Honduras',
    'Panama':              'Panama',
    'Costa Rica':          'Costa Rica',
    'Jamaica':             'Jamaika',
    'El Salvador':         'El Salvador',
    'Haiti':               'Haiti',
    'Curacao':             'Curaçao',

    // Zuid-Amerika
    'Brazil':              'Brasilien',
    'Argentina':           'Argentinien',
    'Colombia':            'Kolumbien',
    'Uruguay':             'Uruguay',
    'Ecuador':             'Ecuador',
    'Chile':               'Chile',
    'Venezuela':           'Venezuela',
    'Bolivia':             'Bolivien',
    'Paraguay':            'Paraguay',
    'Peru':                'Peru',

    // Europa
    'Germany':             'Deutschland',
    'France':              'Frankreich',
    'Spain':               'Spanien',
    'England':             'England',
    'Netherlands':         'Niederlande',
    'Portugal':            'Portugal',
    'Belgium':             'Belgien',
    'Italy':               'Italien',
    'Croatia':             'Kroatien',
    'Serbia':              'Serbien',
    'Austria':             'Österreich',
    'Switzerland':         'Schweiz',
    'Denmark':             'Dänemark',
    'Poland':              'Polen',
    'Ukraine':             'Ukraine',
    'Scotland':            'Schottland',
    'Turkey':              'Türkei',
    'Hungary':             'Ungarn',
    'Romania':             'Rumänien',
    'Czech Republic':      'Tschechien',
    'Slovakia':            'Slowakei',
    'Greece':              'Griechenland',
    'Norway':              'Norwegen',
    'Sweden':              'Schweden',
    'Finland':             'Finnland',
    'Slovenia':            'Slowenien',
    'Albania':             'Albanien',
    'Georgia':             'Georgien',
    'Bosnia':              'Bosnien',

    // Afrika
    'Morocco':             'Marokko',
    'Senegal':             'Senegal',
    'Egypt':               'Ägypten',
    'Nigeria':             'Nigeria',
    'Cameroon':            'Kamerun',
    'Ghana':               'Ghana',
    'Ivory Coast':         'Elfenbeinküste',
    'Mali':                'Mali',
    'Algeria':             'Algerien',
    'Tunisia':             'Tunesien',
    'South Africa':        'Südafrika',
    'DR Congo':            'DR Kongo',
    'Cape Verde':          'Kap Verde',
    'Zambia':              'Sambia',
    'Tanzania':            'Tansania',
    'Angola':              'Angola',

    // Azië & Oceanië
    'Japan':               'Japan',
    'South Korea':         'Südkorea',
    'Iran':                'Iran',
    'Saudi Arabia':        'Saudi-Arabien',
    'Australia':           'Australien',
    'Qatar':               'Katar',
    'Iraq':                'Irak',
    'Uzbekistan':          'Usbekistan',
    'Jordan':              'Jordanien',
    'Oman':                'Oman',
    'New Zealand':         'Neuseeland',
  }
};

function teamName(name) {
  const lang = getCurrentLanguage();
  return TEAM_NAMES[lang]?.[name] || name;
}